_wandb:
    value:
        cli_version: 0.23.1
        e:
            6nv7bduk1xvi6aqp7tb71w84btwy7ixw:
                args:
                    - headless=true
                    - task.env.num_envs=1
                    - save_interval=100
                    - wandb.enable=true
                    - wandb.project=bluerov_manual
                    - wandb.name=hover_tank_ppo_run
                codePath: scripts/train_ppo_behavior.py
                codePathLocal: scripts/train_ppo_behavior.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "360095375360"
                        used: "315404574720"
                email: mdeather0056@gmail.com
                executable: /home/md-ether/isaac51/kit/python/bin/python3
                git:
                    commit: d26e091b3895a5b7c799d1751e10e281ab3d31bc
                    remote: https://github.com/eather0056/isacc_train.git
                host: shortname
                memory:
                    total: "66849148928"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/md-ether/MarineGym-main/bluerov_manual/scripts/train_ppo_behavior.py
                python: CPython 3.11.13
                root: /home/md-ether/MarineGym-main/bluerov_manual
                startedAt: "2026-01-29T15:22:42.423104Z"
                writerId: 6nv7bduk1xvi6aqp7tb71w84btwy7ixw
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 13
                - 15
                - 16
            "4": 3.11.13
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
algo:
    value:
        checkpoint_path: null
        name: ppo
        num_minibatches: 16
        ppo_epochs: 4
        priv_actor: false
        priv_critic: false
        train_every: 32
checkpoint_dir:
    value: /home/md-ether/MarineGym-main/bluerov_manual/checkpoints
enable_livestream:
    value: false
env:
    value:
        env_spacing: 20
        max_episode_length: 400
        num_envs: 1
eval_interval:
    value: -1
headless:
    value: true
max_iters:
    value: -1
mode:
    value: train
save_interval:
    value: 100
seed:
    value: 0
sim:
    value:
        device: cpu
        dt: 0.02
        enable_scene_query_support: true
        replicate_physics: true
        substeps: 2
task:
    value:
        action_saturation_penalty: 0.05
        action_transform: null
        behavior_reward:
            avoid_dist: 1.2
            enable: true
            penalty_ignore: 0.3
            replan_dist: 0.8
            reward_avoid: 0.2
            reward_replan: 0.1
            reward_stop: 0.5
            stop_dist: 0.5
        collision_distance: 0.05
        collision_penalty: 1
        controller:
            action_smooth_alpha: 0.8
            allocation_update_every: 1
            gravity_comp_scale: 0
            max_accel: 0.5
            max_force: null
            max_torque: 5
            r_max: 0.6
            rp_kd: 0.8
            rp_kp: 8
            stabilize_rp: true
            thrust_axis: 0
            thrust_sign: 1
            u_max: 0.6
            v_max: 0.4
            vel_kp: 30
            w_max: 0.2
            yaw_rate_kp: 1.5
        debug: true
        debug_interval: 50
        depth_camera:
            clip_range:
                - 0.05
                - 20
            data_type: distance_to_camera
            enable: true
            extra_data_types: []
            fail_limit: 10
            max_range: 10
            min_range_filter: 0.2
            offset:
                - 0.2
                - 0
                - 0
            resolution:
                - 128
                - 72
            rot_offset_deg:
                - 0
                - -90
                - 0
            viz_every: 0
        depth_obs:
            downsample:
                - 16
                - 9
            enable: true
        disturbances:
            eval:
                flow:
                    enable_flow: false
                    flow_velocity_gaussian_noise:
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                    max_flow_velocity:
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                payload:
                    enable_payload: false
                    mass:
                        - 1
                        - 1
                    z:
                        - 0
                        - 0
            play:
                flow:
                    enable_flow: false
                    flow_velocity_gaussian_noise:
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                    max_flow_velocity:
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                payload:
                    enable_payload: false
                    mass:
                        - 1
                        - 1
                    z:
                        - 0
                        - 0
            train:
                flow:
                    enable_flow: false
                    flow_velocity_gaussian_noise:
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                    max_flow_velocity:
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                        - 0
                payload:
                    enable_payload: false
                    mass:
                        - 1
                        - 1
                    z:
                        - 0
                        - 0
        drone_model:
            controller: LeePositionController
            name: BlueROV
        env:
            env_spacing: 20
            max_episode_length: 400
            num_envs: 1
        force_sensor: false
        goal_spawn_ranges:
            x_range:
                - 0.8
                - 19.2
            y_range:
                - 0.8
                - 5.2
            z_range:
                - 0
                - -1
        maze_walls:
            enable: false
            height: 0.6
            length: 1.4
            num: 10
            spawn_ranges:
                x_range:
                    - 0.8
                    - 19.2
                y_range:
                    - 0.8
                    - 5.2
                z_range:
                    - -0.8
                    - -0.8
            thickness: 0.12
            yaw_options_deg:
                - 0
                - 90
        name: HoverTankPPO
        obstacle_penalty: 0.5
        obstacle_threshold: 1
        obstacles:
            amp:
                - 1.5
                - 1.2
                - 0
            enable: true
            height: 0.5
            line_axis: "y"
            motion: line
            num: 5
            radius: 0.25
            spawn_ranges:
                x_range:
                    - 1
                    - 16
                y_range:
                    - 0.5
                    - 6
                z_range:
                    - -1.3
                    - -0.2
            speed: 0.5
        occ_grid:
            enable: true
            grid_range: 5
            grid_size: 24
        planner:
            avoidance_offset: 1
            bounds_max:
                - 20
                - 6
                - 2
            bounds_min:
                - 0
                - 0
                - -2
            goal_sample_rate: 0.1
            goal_tolerance: 1
            max_iters: 400
            max_speed: 0.3
            max_vert_speed: 0.1
            n_behaviors: 6
            neighbor_radius: 2
            slow_scale: 0.3
            step_size: 1
            wall_margin: 0.3
        planner_stack:
            enable: true
            fusion:
                avoidance_offset: 1
                max_speed: 0.3
                max_vert_speed: 0.1
                slow_scale: 0.3
                yaw_align_speed_scale: 0
                yaw_align_threshold: 0.6
                yaw_kd: 0.2
                yaw_kp: 2
            policy:
                front_safety_deg: 90
                min_range_avoid: 1
                min_range_replan: 0.7
                min_range_stop: 0.4
                stuck_replan_steps: 60
                stuck_speed_thresh: 0.02
                use_front_safety: true
            rrt:
                bounds_max:
                    - 20
                    - 6
                    - 2
                bounds_min:
                    - 0
                    - 0
                    - -2
                goal_sample_rate: 0.1
                goal_tolerance: 1
                max_iters: 400
                neighbor_radius: 2
                plot_3d: false
                plot_every: 0
                plot_gif: false
                plot_gif_every: 5
                plot_history: 50
                step_size: 1
                wall_margin: 0.3
                waypoint_tol: 1.2
            safety:
                max_speed: 0.5
                min_range: 0.6
            sonar:
                debug_first_hit: true
                fov_deg: 120
                hit_path_allow:
                    - /tank
                    - /obstacles
                    - /maze_walls
                hit_path_deny:
                    - /target
                    - /BlueROV
                ignore_empty_path: true
                include_angle_encoding: true
                max_range: 10
                min_range_filter: 0.2
                num_rays: 64
                origin_offset: 0.1
        reset_cooldown_steps: 5
        reward_action_smoothness_weight: 0
        reward_distance_scale: 1.2
        reward_effort_weight: 0.1
        reward_forward_weight: 0.05
        reward_goal_progress: 1.5
        reward_waypoint_bonus: 0.3
        sim:
            device: cpu
            dt: 0.02
            enable_scene_query_support: true
            replicate_physics: true
            substeps: 2
        sonar:
            debug_first_hit: true
            fov_deg: 360
            hit_path_deny:
                - /target
                - /BlueROV
            ignore_empty_path: true
            include_angle_encoding: true
            max_range: 10
            min_range_filter: 0.2
            num_rays: 64
            origin_offset: 0.1
        spawn_ranges:
            x_range:
                - 0.8
                - 19.2
            y_range:
                - 0.8
                - 5.2
            z_range:
                - 0
                - -1
        success_bonus: 5
        success_distance: 0.6
        surface_penalty: 0.2
        tank_usd_path: /home/md-ether/MarineGym-main/bluerov_manual/../marinegym/robots/assets/usd/BlueROV/tank.usd
        terminate_on_collision: true
        termination:
            enable: true
            max_distance: 50
            max_z: 0
            min_z: -2
        tilt_limit_deg: 10
        tilt_penalty_weight: 0.05
        tilt_slow_scale: 0.2
        time_encoding: false
        use_waypoint_reward: true
        viewer:
            eye:
                - 3
                - 3
                - 3
            lookat:
                - 0
                - 0
                - 2
            resolution:
                - 1280
                - 720
        yaw_align_reward_weight: 0.03
        yaw_blend_gain: 0.4
        yaw_blend_thresh: 0.15
total_frames:
    value: 2000000
viewer:
    value:
        eye:
            - 3
            - 3
            - 3
        lookat:
            - 0
            - 0
            - 2
        resolution:
            - 1280
            - 720
wandb:
    value:
        enable: true
        name: hover_tank_ppo_run
        project: bluerov_manual
        tags: []
